# Generated by Django 4.2.11 on 2024-06-19 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('class_name', models.CharField(max_length=5, verbose_name='class_name')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StudentsMarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='subject')),
                ('mark', models.IntegerField(default=5, verbose_name='mark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'students_mark',
                'verbose_name_plural': 'students_marks',
                'db_table': 'students_marks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='students_name_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsmarks',
            index=models.Index(fields=['student_id'], name='students_marks_student_id_idx'),
        ),
    ]
